name: to_do_list
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'


dependencies:

  flutter:
    sdk: flutter
  # flex_color_scheme: ^7.2.0
  # equatable: ^2.0.5
  # flutter_riverpod: ^2.3.6
  # font_awesome_flutter: ^10.5.0
  # gap: ^3.0.1
  # go_router: ^10.0.0
  # google_fonts: ^5.1.0
  # intl: ^0.18.1
  # path: ^1.8.3
  # sqflite: ^2.3.0
  sqflite: ^2.0.0+4
  path: 


  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/todo.png"
  # min_sdk_android: 21 #
 


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
 - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    - family: Tilt Neon
      fonts:
       
        - asset: fonts/TiltNeon-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
